title: Amber Zhang — Data Portfolio
description: Selected analytics projects, dashboards, and case studies.
theme: minima
author:
  name: Amber Zhang
minima:
  social_links:
    - platform: github
      user_url: https://github.com/YOUR_GITHUB_USERNAME
    - platform: linkedin
      user_url: https://www.linkedin.com/in/YOUR_LINKEDIN_SLUG
# Build settings
markdown: kramdown
kramdown:
  input: GFM